# See: https://docs.github.com/en/actions/creating-actions
name: Terraform AutoDocs Action
author: FreeAgent
description: Auto generates documentation for terraform modules.
inputs:
    directories:
      description: List of directories containing terraform files.
      required: true
    options:
      description: Optional configuration arguments.
      required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
